import React from "react";

const Highlight = ({children}: { children: string }) => <span style={{backgroundColor: "gold"}}>{children}</span>;

const DCBYvsCCBY = () => {
    return <div className={"comparison"}>
        <div className={"licenses-name"}>
            <a href="https://creativecommons.org/licenses/by/4.0/">CC 4.0 BY</a>
        </div>
        <div
            className={"licenses-name"}>
            DC 0.1 BY
        </div>
        <div>
            <p>
                This license lets others distribute, remix, tweak, and build upon your work,
                even commercially, as long as they credit you for the original creation.
            </p>
        </div>
        <div>
            <p>
                This license lets others distribute, remix, tweak, and build upon your work,
                even
                commercially, as long as they credit you for the original creation <Highlight> and to an
                extent
                practicable, value generated by
                the attribution is passed to you, the author</Highlight>.
            </p>

        </div>
        <div>
            <h5>Attribution</h5>
            <p>
                You must give appropriate credit, provide a link to the license,
                and
                indicate if changes were made. You may do so in any reasonable manner, but not
                in
                any way that suggests the licensor endorses you or your use.

            </p>
        </div>
        <div>
            <h5>Attribution</h5>
            <p>
                You must give appropriate credit, provide a link to the license,
                <Highlight> provide a link to an URI under direct author control</Highlight> and
                indicate if changes
                were
                made. You may do so in any reasonable manner, but not in any way that suggests the
                licensor endorses you or
                your use.
            </p>

        </div>
        <div>
            <h5>
                URI requirements
            </h5>
            <p>
                To the extent practicable, URI or link to the material if
                supplied.
            </p>
        </div>
        <div>
            <h5>
                URI requirements
            </h5>
            <p> To the extent practicable, URI or link to the material <Highlight>entry on the
                distributed commons registry</Highlight>.
            </p>
        </div>
        <div>
            <h5>Platform requirements</h5>
            <p>
                N/A
            </p>
        </div>
        <div>
            <h5>Platform requirements</h5>
            <p>
                <Highlight>
                    Any website that hosts DC licensed content is explicitly forbidden to provide attribution linking to
                    any URI that is not under direct author control.
                </Highlight>
            </p>
        </div>
    </div>;
};
export default DCBYvsCCBY;
